services:
  app:
    build: .
    ports:
      - "${TG_BOT_PORT}:${TG_BOT_PORT}"
    environment:
      DEBUG: ${DEBUG}
      LOG_LEVEL: ${LOG_LEVEL}
      TG_BOT_PORT: ${TG_BOT_PORT}
      GATEWAY_HOST: ${GATEWAY_HOST}
      GATEWAY_PORT: ${GATEWAY_PORT}
      ADMIN_ID: ${ADMIN_ID}
      REDIS_URL: ${REDIS_URL}
      BOT_TOKEN: ${BOT_TOKEN}
      ABS_IMG_PATH: ${ABS_IMG_PATH}
      VERSION: ${VERSION}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - bot-network

  redis:
    image: redis:7.2-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: [ 'CMD', 'redis-cli', ping ]
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      - bot-network
    restart: unless-stopped

networks:
  bot-network:
    driver: bridge
    name: tg-bot-network

